# Generated by Django 3.0.6 on 2020-12-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendersMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('vender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authuser.Venders')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authuser.Customers')),
            ],
        ),
    ]
