# Generated by Django 3.0.6 on 2020-12-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorsMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authuser.Vendors')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authuser.Customers')),
            ],
        ),
    ]
