# Generated by Django 3.1.4 on 2020-12-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendors',
            old_name='cod_availabel',
            new_name='cod_available',
        ),
    ]
