# Generated by Django 3.1.4 on 2021-01-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authuser', '0003_auto_20210122_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
