# Generated by Django 3.0.6 on 2021-03-02 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authuser', '__first__'),
        ('ManageShops', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateTimeField()),
                ('total_amount', models.PositiveIntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authuser.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authuser.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageOrders.Orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageShops.Products')),
            ],
        ),
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('placed', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(blank=True)),
                ('delivery_date', models.DateTimeField(blank=True)),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Authuser.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authuser.Customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageShops.Products')),
            ],
        ),
    ]
