# Generated by Django 3.0.6 on 2021-03-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageOrders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cartdetails',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='cartdetails',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='cartdetails',
            name='placed',
        ),
    ]
