# Generated by Django 3.0.6 on 2021-03-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authuser', '__first__'),
        ('ManageOrders', '0002_auto_20210303_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authuser.Address'),
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='placed',
            field=models.BooleanField(default=False),
        ),
    ]
