# Generated by Django 3.0.6 on 2021-01-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageShops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
