# Generated by Django 3.0.6 on 2021-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageShops', '0002_remove_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
