# Generated by Django 3.1.4 on 2021-01-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageShops', '0002_auto_20210123_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='catagory',
            field=models.CharField(max_length=100),
        ),
    ]
