# Generated by Django 3.0.6 on 2020-12-22 12:34

import ManageReviews.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManageShops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=1000)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageShops.Products')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ManageReviews.models.review_img_directory_path)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageReviews.Reviews')),
            ],
        ),
    ]
