# Generated by Django 3.0.6 on 2021-01-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageReviews', '0002_auto_20210122_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='Product',
            new_name='product',
        ),
    ]
