export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
<<<<<<< HEAD
export const UPDATE_SUCCESS='UPDATE_SUCCESS';
export const UPDATE_FAIL='UPDATE_FAIL';
export const FETCHING_DATA='FETCHING_DATA';
export const FETCHING_COMPLETE = 'FETCHING_COMPLETE';
=======
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_LOADED = 'PRODUCT_LOADED';
export const PRODUCT_LOADING_FAIL = 'PRODUCT_LOADING_FAIL';
export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING';
export const PRODUCT_LIST_LOADED = 'PRODUCT_LIST_LOADED';
export const PRODUCT_LIST_LOADING_FAIL = 'PRODUCT_LIST_LOADING_FAIL';
export const PRODUCT_LIST_UPDATING = 'PRODUCT_LIST_UPDATING';
export const PRODUCT_LIST_UPDATING_FAIL = 'PRODUCT_LIST_UPDATING_FAIL';
export const PRODUCT_ADDING = 'PRODUCT_ADDING';
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const PRODUCT_ADDING_FAIL = 'PRODUCT_ADDING_FAIL';
export const PRODUCT_REMOVED = 'PRODUCT_REMOVED';
export const PRODUCT_EDITED = 'PRODUCT_EDITED';
export const PRODUCT_EDIT_FAIL = 'PRODUCT_EDIT_FAIL';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';
export const PRODUCT_DELETION_FAIL = 'PRODUCT_DELETION_FAIL';
export const PRODUCT_IMAGES_UPLOADED = 'PRODUCT_IMAGES_UPLOADED';
export const PRODUCT_IMAGES_UPLOAD_FAIL = 'PRODUCT_IMAGES_UPLOAD_FAIL';
>>>>>>> 1884c14d534b0ab86b4ba196e9326f5ea34b9db4
